// ⚠ MACHINE-TRANSLATED DRAFTS — PENDING NATIVE / SCHOLARLY REVIEW.
// Urdu (ur) + German (de) draft translations for the Ziyarat wizards' site descriptions
// (factual, not scripture). Index-aligned to WIZARDS[slug].steps in ./wizard-steps.ts.
// Merged at render in WizardScreen.tsx ON TOP of the EN/AR seed; surfaced with a visible
// "draft under review" notice in the wizard. Replace/approve via review or /admin/wizards.
// See /docs/assumptions.md ("Ziyarat UR/DE translations").
import type { WizardSlug } from './wizard-steps-types';

type DraftText = { t: string; b: string };
export type WizardDrafts = Partial<Record<WizardSlug, Array<{ ur?: DraftText; de?: DraftText }>>>;

/** Languages provided only as drafts here (so the UI can flag them as under review). */
export const DRAFT_LOCALES = ['ur', 'de'] as const;

export const WIZARD_DRAFTS: WizardDrafts = {
  'makkah-ziyarat': [
    { ur: { t: 'مسجدِ حرام', b: 'مکہ کی سب سے بڑی مسجد جو خانہ کعبہ کے گرد واقع ہے۔ یہ اسلام کا مقدس ترین مقام اور ہر عمرہ و حج کا مرکز ہے۔' }, de: { t: 'Masjid al-Haram', b: 'Die Große Moschee von Makkah, die die Kaaba umgibt. Die heiligste Stätte des Islam und das Zentrum jeder Umrah und Hadsch.' } },
    { ur: { t: 'خانہ کعبہ اور حجرِ اسود', b: 'غلافِ کعبہ (کسوہ) میں لپٹا ہوا مکعب، جس کی طرف رُخ کر کے دنیا بھر کے مسلمان نماز پڑھتے ہیں۔ اس کے مشرقی کونے میں حجرِ اسود نصب ہے۔' }, de: { t: 'Die Kaaba & der Schwarze Stein', b: 'Der mit der Kiswah verhüllte Würfel, zu dem Muslime weltweit beten. Der Hajar al-Aswad sitzt in seiner östlichen Ecke.' } },
    { ur: { t: 'مقامِ ابراہیم', b: 'مقامِ ابراہیم، جہاں وہ پتھر محفوظ ہے جس پر کھڑے ہو کر سیدنا ابراہیم نے کعبہ کی دیواریں بلند کیں۔ طواف کے بعد اس کے پیچھے دو رکعت نماز پڑھیں۔' }, de: { t: 'Maqam Ibrahim', b: 'Die Station Ibrahims, die den Stein enthält, auf dem er stand, während er die Kaaba errichtete. Beten Sie nach dem Tawaf zwei Rak’ah dahinter.' } },
    { ur: { t: 'صفا و مروہ', b: 'وہ دو پہاڑیاں جن کے درمیان سعی کی جاتی ہے، جو سیدہ ہاجرہ کی اسماعیل کے لیے پانی کی تلاش کی یاد دلاتی ہیں۔ سات چکر اس عمل کو مکمل کرتے ہیں۔' }, de: { t: 'Safa & Marwah', b: 'Die zwei Hügel, zwischen denen beim Sa’i gegangen wird, zur Erinnerung an Hajars Suche nach Wasser für Ismail. Sieben Durchgänge vollenden den Ritus.' } },
    { ur: { t: 'چاہِ زمزم', b: 'وہ بابرکت چشمہ جو ہزاروں سال سے خانہ کعبہ کے پہلو میں جاری ہے۔ کھل کر پیئں؛ پورے حرم میں کولر موجود ہیں۔' }, de: { t: 'Der Brunnen von Zamzam', b: 'Die gesegnete Quelle, die seit Jahrtausenden neben der Kaaba fließt. Trinken Sie reichlich; in der ganzen Moschee gibt es Kühler.' } },
    { ur: { t: 'جبلِ نور اور غارِ حرا', b: 'پہاڑِ نور، جس میں غارِ حرا واقع ہے جہاں نبی ﷺ پر پہلی وحی نازل ہوئی۔' }, de: { t: 'Jabal al-Nour & Hira', b: 'Der Berg des Lichts, der die Höhle von Hira birgt, wo dem Propheten ﷺ die erste Offenbarung zuteilwurde.' } },
    { ur: { t: 'جبلِ ثور', b: 'وہ پہاڑ جس کے غار نے مدینہ کی ہجرت کے دوران نبی ﷺ اور سیدنا ابوبکر کو پناہ دی۔' }, de: { t: 'Jabal Thawr', b: 'Der Berg, dessen Höhle den Propheten ﷺ und Abu Bakr während der Hidschra nach Madinah Schutz bot.' } },
    { ur: { t: 'منیٰ', b: 'خیموں کی وادی جہاں حجاج حج کے دوران قیام کرتے ہیں اور جمرات کی رمی کرتے ہیں۔' }, de: { t: 'Mina', b: 'Das Tal der Zelte, in dem die Pilger während der Hadsch verweilen und die Steinigung der Dschamarat vollziehen.' } },
    { ur: { t: 'عرفات اور جبلِ رحمت', b: 'وہ میدان جہاں حجاج 9 ذی الحجہ کو وقوف کرتے ہیں — جو حج کی روح ہے — جبلِ رحمت کے پہلو میں۔' }, de: { t: 'Arafat & Jabal al-Rahmah', b: 'Die Ebene, auf der die Pilger am 9. Dhul-Hidscha stehen — das Wesen der Hadsch — neben dem Berg der Barmherzigkeit.' } },
    { ur: { t: 'مزدلفہ', b: 'کھلا میدان جہاں حجاج عرفات کے بعد رات گزارتے ہیں اور منیٰ میں رمی کے لیے کنکریاں جمع کرتے ہیں۔' }, de: { t: 'Muzdalifah', b: 'Die offene Ebene, auf der die Pilger nach Arafat die Nacht verbringen und Kieselsteine für die Steinigung in Mina sammeln.' } },
    { ur: { t: 'جنت المعلّیٰ', b: 'مکہ کا تاریخی قبرستان، جہاں سیدہ خدیجہ رضی اللہ عنہا اور نبی ﷺ کے خاندان کے بہت سے افراد آسودۂ خاک ہیں۔' }, de: { t: 'Jannat al-Mu’alla', b: 'Der historische Friedhof von Makkah, Ruhestätte von Khadijah (r.) und vielen Mitgliedern der Familie des Propheten.' } },
    { ur: { t: 'مسجدِ عائشہ (تنعیم)', b: 'حرم کی حدود سے باہر سب سے قریبی میقات، جہاں سے اہلِ مکہ اور زائرین نئے عمرہ کے لیے احرام باندھتے ہیں۔' }, de: { t: 'Masjid Aisha (Tan’im)', b: 'Der nächstgelegene Miqat außerhalb der Haram-Grenze, wo Bewohner und Besucher Makkahs für eine neue Umrah den Ihram anlegen.' } },
    { ur: { t: 'مکہ میوزیم', b: 'حرمین شریفین کی تعمیرات کا نمائش گاہ — حرمین کی تاریخ، فن اور عظیم توسیعات کو خوبصورت تفصیل کے ساتھ پیش کرتا ہے۔' }, de: { t: 'Makkah-Museum', b: 'Die Ausstellung zur Architektur der Zwei Heiligen Moscheen — Geschichte, Kunst und die großen Erweiterungen der Haramain, reich detailliert dargestellt.' } },
    { ur: { t: 'حرا کلچرل ڈسٹرکٹ', b: 'جبلِ نور کے دامن میں ایک جدید ثقافتی مرکز، جہاں نمائشِ وحی پہلی وحی کی داستان بیان کرتی ہے۔' }, de: { t: 'Hira-Kulturviertel', b: 'Ein modernes Kulturzentrum am Fuße des Jabal al-Nour, mit der Offenbarungs-Ausstellung, die die Geschichte der ersten Offenbarung erzählt.' } },
    { ur: { t: 'کارخانۂ کسوۂ کعبہ', b: 'شاہ عبدالعزیز کمپلیکس جہاں ماہر کاریگر ہر سال کعبہ کا سیاہ و سنہری غلاف (کسوہ) نئے سرے سے بُنتے ہیں۔' }, de: { t: 'Die Kiswa-Fabrik der Kaaba', b: 'Der König-Abdulaziz-Komplex, in dem die schwarz-goldene Kiswah der Kaaba jedes Jahr von Meisterhandwerkern neu gewebt wird.' } },
    { ur: { t: 'کلاک ٹاور میوزیم', b: 'مکہ رائل کلاک ٹاور کے اندر: وقت کی پیمائش اور علمِ فلکیات پر نمائش گاہیں، اور بالائی منزل پر حرم کے اوپر ایک نظارہ گاہ۔' }, de: { t: 'Uhrturm-Museum', b: 'Im Makkah Royal Clock Tower: Galerien zu Zeitmessung und Astronomie sowie eine Aussichtsplattform im obersten Stockwerk über dem Haram.' } },
  ],
  'madina-ziyarat': [
    { ur: { t: 'مسجد نبوی', b: 'نبی کریم ﷺ کی مسجد، اسلام کا دوسرا مقدس ترین مقام، جسے خود نبی ﷺ نے تعمیر کیا، اور آپ ﷺ کی آرام گاہ پر سبز گنبد (Green Dome) اس کی زینت ہے۔' }, de: { t: 'Masjid an-Nabawi', b: 'Die Prophetenmoschee, die zweitheiligste Stätte des Islam, vom Propheten ﷺ selbst erbaut und gekrönt von der Grünen Kuppel (Green Dome) über seiner Ruhestätte.' } },
    { ur: { t: 'الروضہ الشریفہ', b: 'نبی کریم ﷺ کے منبر اور آپ کے حجرے کے درمیان بابرکت جگہ — “جنت کے باغوں میں سے ایک باغ”۔ یہاں نماز پڑھیں اور دعا کریں۔' }, de: { t: 'Ar-Rawdah ash-Sharifah', b: 'Der gesegnete Bereich zwischen der Kanzel des Propheten ﷺ und seiner Kammer — “ein Garten aus den Gärten des Paradieses”. Bete und mache hier Dua.' } },
    { ur: { t: 'جنت البقیع', b: 'مدینہ کا مرکزی قبرستان، مسجد کے پہلو میں، جہاں نبی کریم ﷺ کے بہت سے صحابہ اور اہلِ بیت آرام فرما ہیں۔' }, de: { t: 'Jannat al-Baqi', b: 'Der Hauptfriedhof von Madinah, neben der Moschee, Ruhestätte vieler Gefährten und Familienangehöriger des Propheten ﷺ.' } },
    { ur: { t: 'مسجد قبا', b: 'اسلام میں تعمیر ہونے والی سب سے پہلی مسجد۔ گھر سے وضو کر کے یہاں نماز پڑھنے کا ثواب ایک عمرے کے برابر ہے۔' }, de: { t: 'Masjid Quba', b: 'Die erste im Islam erbaute Moschee. Ein Gebet hier, nachdem man zu Hause die Gebetswaschung vollzogen hat, trägt den Lohn einer Umrah.' } },
    { ur: { t: 'مسجد القبلتین', b: 'دو قبلوں والی مسجد، جہاں نماز کے دوران بیت المقدس سے کعبہ کی طرف رخ پھیرنے کا حکم نازل ہوا۔' }, de: { t: 'Masjid al-Qiblatayn', b: 'Die Moschee der zwei Gebetsrichtungen, wo der Befehl kam, sich mitten im Gebet von Jerusalem zur Kaaba zu wenden.' } },
    { ur: { t: 'جبلِ احد', b: 'غزوۂ احد کا پہاڑ، جس کے بارے میں نبی کریم ﷺ نے فرمایا: “احد ایک پہاڑ ہے جو ہم سے محبت کرتا ہے اور ہم اس سے محبت کرتے ہیں۔”' }, de: { t: 'Mount Uhud', b: 'Der Berg der Schlacht von Uhud, über den der Prophet ﷺ sagte: “Uhud ist ein Berg, der uns liebt und den wir lieben.”' } },
    { ur: { t: 'شہدائے احد', b: 'احد کے ستر شہداء کی آرام گاہ، جن میں نبی کریم ﷺ کے چچا حضرت حمزہ رضی اللہ عنہ بھی شامل ہیں۔' }, de: { t: 'Die Märtyrer von Uhud', b: 'Die Ruhestätte der siebzig Märtyrer von Uhud, darunter Hamza (radiya Allahu anhu), der Onkel des Propheten ﷺ.' } },
    { ur: { t: 'ساتوں مساجد', b: 'غزوۂ خندق (الخندق) کے مقام کے قریب چھوٹی تاریخی مساجد، جہاں احزاب (متحدہ لشکروں) کو پسپا کیا گیا۔' }, de: { t: 'Die Sieben Moscheen', b: 'Kleine historische Moscheen nahe dem Ort der Grabenschlacht (al-Khandaq), wo die Verbündeten zurückgeschlagen wurden.' } },
    { ur: { t: 'مسجد الغمامہ', b: 'حرم کے قریب ایک تاریخی مسجد، روایت کے مطابق وہ مقام جہاں نبی کریم ﷺ نے نمازِ استسقاء (بارش کی دعا) اور نمازِ عید ادا کی۔' }, de: { t: 'Masjid al-Ghamamah', b: 'Eine historische Moschee nahe dem Haram, überliefert als der Ort, an dem der Prophet ﷺ das Regengebet und das Eid-Gebet verrichtete.' } },
    { ur: { t: 'کھجور بازار · عجوہ', b: 'مدینہ اپنی کھجوروں کے لیے مشہور ہے، خاص طور پر عجوہ جس کی نبی کریم ﷺ نے تعریف فرمائی۔ قبا کے قریب کھجور بازار کی سیر کریں۔' }, de: { t: 'Der Dattelmarkt · Ajwa', b: 'Madinah ist berühmt für seine Datteln, besonders die vom Propheten ﷺ gelobte Ajwa. Besuche den Dattelmarkt nahe Quba.' } },
    { ur: { t: 'نمائشِ سیرتِ نبوی', b: 'نبی کریم ﷺ کی زندگی، کردار اور میراث پر السلام (As-Salam) کی عظیم نمائش، حرم کے پہلو میں عمیق ملٹی میڈیا ہالوں کے ساتھ۔' }, de: { t: 'Ausstellung der Prophetenbiografie', b: 'Die große As-Salam-Ausstellung über Leben, Charakter und Vermächtnis des Propheten ﷺ, mit eindrucksvollen Multimedia-Sälen neben dem Haram.' } },
    { ur: { t: 'دار المدینہ میوزیم', b: 'ایک ثقافتی میوزیم جو مدینہ کی شہری اور سماجی تاریخ کو بیان کرتا ہے، پرانے شہر اور اس کی مساجد کے تفصیلی نمونوں (ماڈلز) کے ساتھ۔' }, de: { t: 'Dar Al Madinah Museum', b: 'Ein Heimatmuseum, das die städtische und gesellschaftliche Geschichte Madinahs nachzeichnet, mit detaillierten Modellen der Altstadt und ihrer Moscheen.' } },
    { ur: { t: 'نمائشِ قرآن کریم', b: 'قرآن کے نزول، حفاظت اور فنون کے لیے مختص ایک میوزیم، مسجد نبوی سے تھوڑی ہی مسافت پر۔' }, de: { t: 'Ausstellung des Heiligen Quran', b: 'Ein Museum, das der Offenbarung, Bewahrung und den Künsten des Quran gewidmet ist, nur einen kurzen Spaziergang von Masjid an-Nabawi entfernt.' } },
    { ur: { t: 'حجاز ریلوے میوزیم', b: 'بحال شدہ عثمانی ریلوے اسٹیشن اور میوزیم، جو دمشق سے مدینہ تک کے تاریخی ریلوے خط کی کہانی سناتا ہے۔' }, de: { t: 'Hijaz-Eisenbahnmuseum', b: 'Der restaurierte osmanische Bahnhof und das Museum, die die Geschichte der historischen Strecke von Damaskus nach Madinah erzählen.' } },
  ],
};
